### ISSUE TITLE
Error trying to run example for planning mission

### ISSUE THREAD

**Issue by intiluna** [gisma-courses/LV-uav-workflow#1]
Hello Dear Dev Team,

I am trying to run the example described in https://gisma-courses.github.io/LV-uav-workflow/morea/UAVFieldwork/experiences-uavRmp.html

I am using:
Windows 11 pro
R  version 4.2.0 (2022-04-22 ucrt) -- "Vigorous Calisthenics"
Rstudio "Prairie Trillium" Release (8aaa5d47, 2022-03-17) build 461

After installing the library I tried to run the example:
# get example DEM data
 
 fn <- system.file("extdata", "mrbiko.tif", package = "uavRmp")
 fa <- system.file("extdata", "flightarea.kml", package = "uavRmp") 

I checked that fn and fa have the correct location but when running:

   fp<-makeAP(surveyArea= fa,
                        useMP  = TRUE,
                        flightAltitude = 120, 
                        maxSpeed = 35,
                       demFn = fn)

I get the message:

setup environ and params...
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                              <?xml version="1.0" encoding="U
                    (right here) ------ points at ?

What should I be checking to have it right? Thank you very much for your help,
Inti

**Comment by gisma** [comment]
@ILunaA  Sorry for answering so late. Well I checked it is just not implemented any more . I will fix it asap. Please check the new workflow using the original .plan files which now works also for DJI.
cheers Chris
